# Header
menu:
  首页: /
  归档: /archives
  关于: /about
# rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
# - tagcloud
- follow_mes
# - recommend_posts
- archive
- recent_comments

# - official_accounts
- recent_posts
# - tag
- links

# Links
links:
  SegmentFault: https://segmentfault.com/

# recommend_posts
recommend_posts:
  《JavaScript 闯关记》: /2016/07/24/javascript-lesson-readme/

# Miscellaneous
google_analytics:
favicon: /img/001.jpg
twitter:  /img/001.jpg
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: shijiajie

# Baidu share
baidushare: true

# Baidu statistic
baidu_tongji: true

# 文章尾部声明
statement: true
statement_img: https://s2.ax1x.com/2019/05/07/ErhHTP.md.jpg
# https://s2.ax1x.com/2019/05/07/ErhHTP.md.jpg

# 微信公众号展示
# official_accounts_img: https://s2.ax1x.com/2019/05/07/ErhHTP.md.jpg
# official_accounts_text: 订阅「石佳劼的博客」

# 关注我
follow_mes:
  我的「微博」: https://weibo.com/u/5572436107
  我的「知乎」: https://www.zhihu.com/people/gao-ye-64-7
  我的「博客园」: https://www.cnblogs.com/yeran
  我的「V2EX」: https://www.v2ex.com/member/gaoyexyz
  我的「GitHub」: https://github.com/gao-ye

# 网站备案号
website_icp: 粤ICP备15013245号-2
