# Header
menu:
  首页: /
  归档: /archives
  关于: /about
# rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- follow_mes
- archive
- recent_comments
- recent_posts
- links

# Links
links:
  SegmentFault: https://segmentfault.com/



# Miscellaneous
google_analytics:
favicon: /img/001.jpg
twitter:  /img/001.jpg
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: shijiajie

# Baidu share
baidushare: true

# Baidu statistic
baidu_tongji: true

# 文章尾部声明
statement: true
statement_img: https://s2.ax1x.com/2019/05/07/ErhHTP.md.jpg



# 关注我
follow_mes:
  我的「微博」: https://weibo.com/u/5572436107
  我的「知乎」: https://www.zhihu.com/people/gao-ye-64-7
  我的「博客园」: https://www.cnblogs.com/yeran
  我的「V2EX」: https://www.v2ex.com/member/gaoyexyz
  我的「GitHub」: https://github.com/gao-ye
  我的「主页」: https://gaoye.xyz

# 网站备案号
website_icp: 皖ICP备19015192号
